name: Radar Deployment

on:
  push:
    branches:
      - radar-update

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./radar
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install
        run: npm install

      - name: nuxt generate
        run: npm run generate
        #env:
        #  BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: radar-build
          path: radar/dist
          if-no-files-found: error

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          ref: deploy

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: radar-build
          path: radar

      - name: Configure git
        run: |
          git config --global user.email "aachen@techlabs.org"
          git config --global user.name "TechLabs Aachen GitHub Radar Workflow"

      - name: Commit deploy repo
        run: |
          git add --all --force radar
          git commit -m "Add frontend build at $(date +%FT%T%Z)" --allow-empty
        working-directory: radar

      - name: Push deploy repo
        run: git push
        working-directory: radar
